stages:
  - docker
  - helm

docker:
  stage: docker
  script:
    - VERSION=$(cat version)
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build . -t $CI_REGISTRY_IMAGE:$VERSION
    - docker push $CI_REGISTRY_IMAGE:$VERSION
  only:
    - main
  tags:
    - libvision

helm:
  stage: helm
  image: dtzar/helm-kubectl
  script:
    - VERSION=$(cat version)
    - kubectl apply -f ./deployment.yaml -n redash
  only:
    - main
  tags:
    - libvision
