---
variables:
  TAG: 0.1.12
  NAMESPACE: vision

stages:
  - deploy_docker
  - deploy_helm

deploy_docker:
  stage: deploy_docker
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build . -t $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$TAG
    - docker push $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$TAG
  only:
    - main
  tags:
    - docker

deploy_helm:
  stage: deploy_helm
  image: dtzar/helm-kubectl
  script:
    - helm repo add chartmuseum $CHARTMUSEUM
    - helm upgrade vision chartmuseum/template
      --install 
      --atomic
      --namespace $NAMESPACE 
      --create-namespace 
      --set image.repository=$CI_REGISTRY_IMAGE
      --set image.tag=$TAG 
      --set env.TNT_USER=$TNT_USER 
      --set env.TNT_PASSWORD=$TNT_PASSWORD 
      --set env.TNT_HOST=$TNT_HOST 
      --set env.TNT_PORT=$TNT_PORT
      -f .ci/values.yaml
  except:
    - main
  tags:
    - docker
