variables:
  NAMESPACE: redash

stages:
  - docker
  - kubernetes

docker:
  stage: docker
  script:
    - VERSION=$(cat version)
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build . -t $CI_REGISTRY_IMAGE:$VERSION
    - docker push $CI_REGISTRY_IMAGE:$VERSION
  only:
    - main
  tags:
    - libvision

kubernetes:
  stage: kubernetes
  image: dtzar/helm-kubectl
  script:
    - VERSION=$(cat version)
    - sed -i "s/<VERSION>/$VERSION/g" .ci/deployment.yaml
    - sed -i "s/<POSTGRES_USER>/$POSTGRES_USER/g" .ci/deployment.yaml
    - sed -i "s/<POSTGRES_PASSWORD>/$POSTGRES_PASSWORD/g" .ci/deployment.yaml
    - sed -i "s/<POSTGRES_HOST>/$POSTGRES_HOST/g" .ci/deployment.yaml
    - sed -i "s/<POSTGRES_PORT>/$POSTGRES_PORT/g" .ci/deployment.yaml
    - sed -i "s/<POSTGRES_DB>/$POSTGRES_DB/g" .ci/deployment.yaml
    - kubectl apply -f .ci/deployment.yaml --namespace $NAMESPACE
    - kubectl apply -f .ci/service.yaml --namespace $NAMESPACE
    - kubectl apply -f .ci/ingress.yaml --namespace $NAMESPACE
  only:
    - main
  tags:
    - libvision
