variables:
  TAG: 0.1.12
  NAMESPACE: vision

stages:
  - deploy_docker
  - deploy_helm
  #- deploy_ansible

deploy_docker:
  stage: deploy_docker
  script:
    #- docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build . -t $CI_REGISTRY/provisioner/$CI_PROJECT_NAME:$TAG
    - docker push $CI_REGISTRY/provisioner/$CI_PROJECT_NAME:$TAG
  except:
    - main
  tags:
    - worker

#deploy_ansible:
#  stage: deploy_ansible
#  script:
#    - ansible-playbook ./.ci/playbook.yml
#      -e "image=$CI_REGISTRY/provisioner/$CI_PROJECT_NAME:$TAG"
#      -e "network=vision"
#  except:
#    - main
#  tags:
#    - worker

deploy_helm:
  stage: deploy_helm
  script:
    - helm repo add template https://$HARBOR_URI/chartrepo/library
    - helm upgrade vision template/template
      --install 
      --atomic
      --namespace $NAMESPACE 
      --create-namespace 
      --set image.tag=$TAG 
      --set env.TNT_USER=$TNT_USER 
      --set env.TNT_PASSWORD=$TNT_PASSWORD 
      --set env.TNT_HOST=$TNT_HOST 
      --set env.TNT_PORT=$TNT_PORT
      -f .ci/values.yaml
  only:
    - main
  tags:
    - worker
