version: '2'

services:
  tarantool1:
    image: tarantool/tarantool:1.10.2
    restart: always
    environment:
      TARANTOOL_REPLICATION: "tarantool1,tarantool2"
      TARANTOOL_USER_NAME: tnt_user
      TARANTOOL_USER_PASSWORD: tnt_password
    networks:
      - mynet
    ports:
      - "3301:3301"

  tarantool2:
    image: tarantool/tarantool:1.10.2
    restart: always
    environment:
      TARANTOOL_REPLICATION: "tarantool1,tarantool2"
      TARANTOOL_USER_NAME: tnt_user
      TARANTOOL_USER_PASSWORD: tnt_password
    networks:
      - mynet
    ports:
      - "3302:3301"

networks:
  mynet:
    driver: bridge
