version: '2'

services:
  tarantool1:
    image: tarantool/tarantool:1.10.2
    restart: always
    environment:
      TARANTOOL_REPLICATION: "tarantool1,tarantool2"
      TARANTOOL_USER_NAME: ${TNT_USER}
      TARANTOOL_USER_PASSWORD: ${TNT_PASSWORD}
    networks:
      - mynet
    ports:
      - "3301:3301"

  tarantool2:
    image: tarantool/tarantool:1.10.2
    restart: always
    environment:
      TARANTOOL_REPLICATION: "tarantool1,tarantool2"
      TARANTOOL_USER_NAME: ${TNT_USER}
      TARANTOOL_USER_PASSWORD: ${TNT_PASSWORD}
    networks:
      - mynet
    ports:
      - "3302:3301"

  redpanda:
    image: docker.vectorized.io/vectorized/redpanda:latest
    container_name: redpanda-1
    ports:
      - 9092:9092
      - 9644:9644
    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp
      - "1"
      - --memory
      - 1G
      - --reserve-memory
      - 0M
      - --node-id
      - "0"
      - --check=false

networks:
  mynet:
    driver: bridge
