variables:
  TAG: 0.1.9
  NAMESPACE: cv

stages:
  - stage: build
    script:
      - docker build . -t $HARBOR_URI/library/vision:$TAG
      - docker push $HARBOR_URI/library/vision:$TAG
    only:
      - main
  - stage: deploy
    script:
      - helm repo add template https://$HARBOR_URI/chartrepo/library
      - helm upgrade vision template/template
        --install 
        --atomic
        --namespace $NAMESPACE 
        --create-namespace 
        --set image.tag=$TAG 
        --set env.TNT_USER=$TNT_USER 
        --set env.TNT_PASSWORD=$TNT_PASSWORD 
        --set env.TNT_HOST=$TNT_HOST 
        --set env.TNT_PORT=$TNT_PORT
        -f .ci/values.yaml
    only:
      - main
