variables:
  TAG: 0.1.4
  NAMESPACE: cv

stages:
  - stage: build
    script:
      - docker build . -t $DOCKER_REGISTRY/library/vision:$TAG
      - docker push $DOCKER_REGISTRY/library/vision:$TAG
  - stage: prepare
    script:
      - docker-compose up --build -d
  - stage: deploy
    script:
      - helm upgrade --install 
        vision .ci 
        --namespace $NAMESPACE 
        --create-namespace 
        --set image.tag=$TAG 
        --set env.TNT_USER=$TNT_USER 
        --set env.TNT_PASSWORD=$TNT_PASSWORD 
        --set env.TNT_HOST=$TNT_HOST 
        --set env.TNT_PORT=$TNT_PORT
