version: 2.1
jobs:
  build:
    docker:
      - image: docker:19.03.13
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t CircleCI-Public/circleci-demo-docker:$TAG .
          #echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
          #docker push CircleCI-Public/circleci-demo-docker:$TAG
