---
- hosts: db1
  become: yes
  tasks:
    - name: install tarantool
      include_tasks: tasks/install.yml

    - name: copy init.lua
      template:
        src: init.lua
        dest: /home/tarantool/init.lua
        owner: tarantool
        mode: 0644
      notify: "restart tarantool"

    - name: copy tarantool.service
      copy:
        src: tarantool.service
        dest: /etc/systemd/system/tarantool.service
        mode: 0644
      notify: "restart tarantool"

  handlers:
    - name: apply changes for service
      systemd:
        name: tarantool.service
        enabled: yes
        daemon_reload: yes
        state: restarted
      listen: "restart tarantool"
