---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vision
  labels:
    app: vision
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vision
  template:
    metadata:
      labels:
        app: vision
    spec:
      containers:
        - name: etl
          image: registry.gitlab.com/libvision/vision:<VERSION>
          imagePullPolicy: Always
          env:
            - name: POSTGRES_USER
              value: <POSTGRES_USER>

            - name: POSTGRES_PASSWORD
              value: <POSTGRES_PASSWORD>

            - name: POSTGRES_HOST
              value: <POSTGRES_HOST>

            - name: POSTGRES_PORT
              value: "<POSTGRES_PORT>"

            - name: POSTGRES_DB
              value: <POSTGRES_DB>
