---
- hosts: worker
  vars:
    git_uri: http://git.vnmntn.com/vnmntn
    repository: vision
    namespace: vision
    tag: 0.1.6
  tasks:
    - name: clone repository
      git:
        repo: "{{ git_uri }}/{{ repository }}"
        dest: "{{ ansible_env.HOME }}/{{ repository }}"
        force: yes
        version: main

    - name: deploy application
      include: playbooks/application.yml

    - name: deploy swagger
      include: playbooks/swagger.yml

    - name: delete content & directory
      file:
        state: absent
        path: "{{ ansible_env.HOME }}/{{ repository }}"
