---
- hosts: worker
  vars:
    git_uri: http://git.vnmntn.com/vnmntn
    repository: vision
    namespace: vision
    tag: 0.1.7
  tasks:
    - name: clone repository
      git:
        repo: "{{ git_uri }}/{{ repository }}"
        dest: "{{ ansible_env.HOME }}/{{ repository }}"
        force: yes
        version: c-main

    - name: "build {{ repository }} and push it to a private repo"
      community.docker.docker_image:
        build:
          path: "{{ ansible_env.HOME }}/{{ repository }}"
        name: "vnmntn/{{ repository }}"
        tag: "{{ tag }}-c"
        push: yes
        source: build

    #- name: deploy application
    #  include: playbooks/application.yml

    #- name: deploy swagger
    #  include: playbooks/swagger.yml

    - name: delete content & directory
      file:
        state: absent
        path: "{{ ansible_env.HOME }}/{{ repository }}"
