---
- name: "build {{ repository }} and push it to a private repo"
  community.docker.docker_image:
    build:
      path: "{{ ansible_env.HOME }}/{{ repository }}"
    name: "vnmntn/{{ repository }}"
    tag: "{{ tag }}"
    push: yes
    source: build

- name: create application service
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: "{{repository}}"
        namespace: "{{namespace}}"
      spec:
        selector:
          app: "{{repository}}"
        ports:
          - name: web
            port: 80
            targetPort: 5000

- name: create application deployment
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: "{{ repository }}"
        namespace: "{{ namespace }}"
        labels:
          app: "{{ repository }}"
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: "{{ repository }}"
        template:
          metadata:
            labels:
              app: "{{ repository }}"
          spec:
            containers:
              - name: "{{ repository }}"
                image: "vnmntn/{{ repository }}:{{ tag }}"
                imagePullPolicy: IfNotPresent
                env:
                  - name: POSTGRES_CONN
                    value: "{{ pg_conn }}"

- name: create application ingress
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: "{{ repository }}"
        namespace: "{{ namespace }}"
        annotations:
          nginx.ingress.kubernetes.io/proxy-body-size: 64m
          nginx.ingress.kubernetes.io/configuration-snippet: |
            more_set_headers "Access-Control-Allow-Origin: $http_origin";
          nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
          nginx.ingress.kubernetes.io/cors-allow-methods: PUT, GET, POST,
            OPTIONS, DELETE, PATCH
          nginx.ingress.kubernetes.io/enable-cors: "true"
      spec:
        ingressClassName: nginx
        rules:
          - host: "api.vnmntn.com"
            http:
              paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                      name: "{{ repository }}"
                      port:
                        number: 80
