- community.docker.docker_compose:
    project_name: tarantool
    definition:
      version: '2'
      services:
        tarantool1:
          image: tarantool/tarantool:2
          container_name: tarantool0
          environment:
            TARANTOOL_REPLICATION: "tarantool1,tarantool2"
            TARANTOOL_USER_NAME: "{{ tnt_user }}"
            TARANTOOL_USER_PASSWORD: "{{ tnt_password }}"
          volumes:
            - tnt0:/opt/tarantool
          networks:
            - mynet
          ports:
            - "3301:3301"

        tarantool2:
          image: tarantool/tarantool:2
          container_name: tarantool1
          environment:
            TARANTOOL_REPLICATION: "tarantool1,tarantool2"
            TARANTOOL_USER_NAME: "{{ tnt_user }}"
            TARANTOOL_USER_PASSWORD: "{{ tnt_password }}"
          volumes:
            - tnt1:/opt/tarantool
          networks:
            - mynet
          ports:
            - "3302:3301"
      volumes:
        tnt0: null
        tnt1: null
      networks:
        mynet:
          driver: bridge
