name: ci

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: self-hosted
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: vnmntn/vision:latest

      - name: Deploy helm
        run: cd .ci && helm upgrade --install . --atomic --namespace vision --create-namespace 
          --set POSTGRES_USER=${{ secrets.POSTGRES_USER }} 
          --set POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} 
          --set POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}
          --set POSTGRES_PORT=${{ secrets.POSTGRES_PORT }}
          --set POSTGRES_DB=${{ secrets.POSTGRES_DB }}
